### PR TITLE
Updated Chat GPT and BARD Code

### PR DESCRIPTION
**Pull request by fvaysh**
This code is for the issue - #25 
Added code for Chat GPT and Bard Integration where we have to set up OPEN API Key or BARD API Key
Then the code calls it as required

### CODE REVIEW

**Comment by rootCircle** [comment]
Hello @fvaysh, congrats on your first PR to this repo! Can you please check in the failing workflows please! Ping me if you need any help regarding that!

I believed you have tested in the code, did you?

**Comment by rootCircle** [comment]
To locally reproduce these errors, try running

```bash
npm run lint
```

**Comment by fvaysh** [comment]
I exhausted my API keys while running it, can u please use an API key in develop.sample.env and run it as a whole so that you can tell me what's the exact error, because the engine-gpt.js was running fine for me

**Comment by Gyan172004** [comment]
We will test it at our end once your code passes all checks, Currently the error is due to Lint Checks.
Check these Lint errors using `npm run lint` locally  and try resolving them. If you have trouble running those commands, surely ping me out!

Before we start reviewing and testing, its important that your code passes all the checks

**Comment by rootCircle** [comment]
Hey @fvaysh, if you're having issues resolving the lint errors, then possibly we can help from our side, just do let us know!

**Pull request closed without merging**
