### PR TITLE
ci [Github Actions] : Added Release.yml

### PR DESCRIPTION
**Pull request by Him7n**
This PR adds a GitHub Actions workflow (release.yml) to automate the release process for the extension. Key changes include:

- Add automated release workflow triggered by version tags
- Configure workflow to package the extension using bun
- Set up automated creation of GitHub releases with assets
- Include version extraction and validation steps
- Configure draft/prerelease settings for manual review

## Related Issue
N/A (or reference any existing issue if applicable)

## Checklist
- [x] I have tested the workflow locally
- [x] Documentation has been updated (CHANGELOG.md will be updated with release details)
- [x] Code follows the project's GitHub Actions workflow conventions
- [x] Code includes necessary comments for workflow steps
- [x] Changes do not introduce new issues to the release process

## Additional Notes
This workflow will help streamline our release process by:
- Automating the packaging of the extension
- Creating consistent GitHub releases
- Ensuring proper version tagging
- Allowing for review before final release through draft status

### CODE REVIEW

**Comment by rootCircle** [comment]
blocked on #72! I will wait for that to complete so that we can incrementally handle chromium and firefox at once

**Comment by rootCircle** [comment]
now since #72 is merged, you can now start working on it, there are few breaking changes (check package.json for reference)

**Comment by Him7n** [comment]
> now since #72 is merged, you can now start working on it, there are few breaking changes (check package.json for reference)

please take a look now :smile:

**Review by rootCircle — APPROVED** [review]

**Comment by rootCircle** [comment]
LGTM :+1: Merged

**Pull request merged**
