### PR TITLE
Minor Readme Enhancements

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
## Proposed Changes
- Updated Discord Img Shield
- Added Img Shields for Made with Love, Stars, License, Issues
- Centered the Extension Store Links

## Preview
image

## Checklist
- [x] I have tested my changes thoroughly.
- [x] I have updated the documentation accordingly.
- [X] My code follows the project's coding conventions and style.
- [x] I have added necessary comments to my code, particularly in complex areas.
- [x] I have ensured that my changes do not introduce any new issues.

### CODE REVIEW

**Comment by rootCircle** [comment]
Looks awesome! 

Mind if you can add PR:Welcome and Build (gh_workflow) label as well?

**Comment by Thunder-Blaze** [comment]
idk if I got this right but do you mean this ?
&nbsp;
or this one ?

**Comment by rootCircle** [comment]
I think second but the content should be just "welcome"

And another workflow for github actions status(aka build workflow)

**Comment by Thunder-Blaze** [comment]
and


these ?
If yes, which one out of the below two to keep or should I keep both
<br><br>

better version ->

**Comment by rootCircle** [comment]
I guess first PR "Welcome and Build" badge was more consistent with the theme, so prefer that instead of this!

Also, for builds check if you can use consistent layouts. If not, move forward with these only!

**Comment by Thunder-Blaze** [comment]
check the updated comment, and btw if it is color problem, I can change them as you want

**Comment by rootCircle** [comment]
Yes change the color as well! Rest all is awesome!

**Comment by Thunder-Blaze** [comment]
&nbsp; 

I've used lint-check.yml (health check) for the 2nd badge
Should I create one for secrets-scanning.yml (gitleaks) too ?

**Comment by rootCircle** [comment]
No it's not required!

**Comment by Thunder-Blaze** [comment]
image

should I finalize this ?

**Comment by rootCircle** [comment]
Looks awesome! Go ahead!🎉🎉

**Comment by Thunder-Blaze** [comment]
Done, you can view the changes here before merging [Readme.md](https://github.com/Thunder-Blaze/docFiller/blob/ReadmeEnhancement/README.md)

**Review by rootCircle — APPROVED** [review]

**Comment by rootCircle** [comment]
LGTM! Thanks for your contribution!

**Pull request merged**
